import type { CardId, CubeBoss, EdgeTower, Enemy, EnemyProjectile, MortarProjectile, Projectile, Tower, WaveTracker } from "../types";
import type { TowerState } from "./towerState";
import type { EnemyState } from "./enemyState";
import type { BossState } from "./bossState";
import type { ProjectileState, EnemyProjectileState, MortarProjectileState } from "./projectileState";
import type { ScheduledBattleAction } from "./battleActions";
import type { LoadoutReselection } from "./loadoutReselection";
import type { TowerShifterSimulation } from "./towerShifterRules";
import type { StoredEnemy } from "./towerStorageRules";
import type { SpellMortarFlight } from "./towerSkillSimulation";
import type { BattleSessionSnapshot } from "./battleSession";
import type { TimedCellSeal } from "./timedCellSeals";
import type { NullifiedTowers } from "./towerNullificationRules";
import type { BattleEntityIdState } from "./battleEntityIds";
import type { CardDeadline } from "./battleLoadout";
import type { TutorialCheckpoint } from "./tutorialState";
import type { BattleLifecycleState } from "./battleLifecycle";
import type { BattleWallet } from "./battleEconomy";

export interface BattleSaveData {
  wallets?: BattleWallet[];
  lifecycle?: BattleLifecycleState;
  tutorial?: TutorialCheckpoint;
  entityIds?: BattleEntityIdState;
  nullifiedTowers?: NullifiedTowers<TowerState>;
  edgeTowers?: EdgeTower[];
  simulation?: BattleSessionSnapshot & { mirrorNextGroupId: number };
  bossPhaseIndex?: number;
  bossPhaseStartedAt?: number;
  bossHomePosition?: { x: number; y: number } | null;
  levelElapsed: number;
  battleTime: number;
  cardTime: number;
  nextNaturalProduceAt: number;
  chars: number;
  baseIntegrity: number;
  wave: number;
  waveTracker: WaveTracker | null;
  enemiesDefeated: number;
  towerOrder: number;
  gameSpeed: number;
  debugModeEnabled?: boolean;
  selectedCardId: CardId;
  cardDeadlines: CardDeadline[];
  autoUpgradeEnabled: boolean;
  autoUpgradeReserveChars: number;
  towers: TowerState[];
  enemies: EnemyState[];
  boss?: BossState | null;
  projectiles: ProjectileState[];
  enemyProjectiles: EnemyProjectileState[];
  mortarProjectiles: MortarProjectileState[];
  actions: ScheduledBattleAction[];
  storage: StoredEnemy<EnemyState, TowerState>[];
  shifter: ReturnType<TowerShifterSimulation["snapshot"]>;
  reselection: ReturnType<LoadoutReselection["snapshot"]>;
  extraction: number;
  spellMortarFlights: SpellMortarFlight[];
  sealedCells: string[];
  timedCellSeals?: TimedCellSeal[];
}

export interface BattleSaveState extends BattleSaveData {
  nullifiedTowers?: NullifiedTowers<Tower>;
  towers: Tower[];
  enemies: Enemy[];
  boss?: CubeBoss | null;
  projectiles: Projectile[];
  enemyProjectiles: EnemyProjectile[];
  mortarProjectiles: MortarProjectile[];
  storage: StoredEnemy<Enemy, Tower>[];
}
