import type { CardId, CubeBoss, EdgeTower, Enemy, EnemyProjectile, MortarProjectile, Projectile, Tower, WaveTracker } from "../types";
import type { ScheduledBattleAction } from "./battleActions";
import type { LoadoutReselection } from "./loadoutReselection";
import type { TowerShifterController } from "./towerShifter";
import type { StoredEnemy } from "./towerStorageRules";
import type { SpellMortarFlight } from "./towerSkills";
import type { BattleSessionSnapshot } from "./battleSession";
import type { TimedCellSeal } from "./timedCellSeals";
import type { NullifiedTowers } from "./towerNullificationRules";
import type { BattleEntityIdState } from "./battleEntityIds";
import type { CardDeadline } from "./battleLoadout";
import type { TutorialCheckpoint } from "./tutorialState";
import type { BattleLifecycleState } from "./battleLifecycle";

export interface BattleSaveState {
  lifecycle?: BattleLifecycleState;
  tutorial?: TutorialCheckpoint;
  entityIds?: BattleEntityIdState;
  nullifiedTowers?: NullifiedTowers<Tower>;
  edgeTowers?: EdgeTower[];
  simulation?: BattleSessionSnapshot & { mirrorNextGroupId: number };
  bossPhaseIndex?: number;
  bossPhaseStartedAt?: number;
  bossHomePosition?: { x: number; y: number } | null;
  levelElapsed: number;
  battleTime: number;
  cardTime: number;
  nextNaturalProduceAt: number;
  chars: number;
  baseIntegrity: number;
  wave: number;
  waveTracker: WaveTracker | null;
  enemiesDefeated: number;
  towerOrder: number;
  gameSpeed: number;
  debugModeEnabled?: boolean;
  selectedCardId: CardId;
  cardDeadlines: CardDeadline[];
  autoUpgradeEnabled: boolean;
  autoUpgradeReserveChars: number;
  towers: Tower[];
  enemies: Enemy[];
  boss?: CubeBoss | null;
  projectiles: Projectile[];
  enemyProjectiles: EnemyProjectile[];
  mortarProjectiles: MortarProjectile[];
  actions: ScheduledBattleAction[];
  storage: StoredEnemy<Enemy, Tower>[];
  shifter: ReturnType<TowerShifterController["snapshot"]>;
  reselection: ReturnType<LoadoutReselection["snapshot"]>;
  extraction: number;
  spellMortarFlights: SpellMortarFlight[];
  sealedCells: string[];
  timedCellSeals?: TimedCellSeal[];
}
